server:
  port: 8086
  # session-timeout: 1000000 #用户回话session过期时间，以秒为单位
  tomcat:
    uri-encoding: UTF-8 #配置Tomcat编码，默认为UTF-8
    compression: on #Tomcat是否开启压缩，默认为关闭
    disableUploadTimeout: false
    accesslog:
      directory: /log
      enabled: true
      pattern: '%{ip}s %{userName}s %t "%r" %s %b %T'
      file-date-format: yyyy-MM-dd
      prefix: access_log.
      suffix: .log

spring:
  jpa:
    database: mysql
    hibernate:
      ddl-auto: update
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    #url: jdbc:mysql://192.168.1.13:3306/fundData?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    url: jdbc:mysql://121.37.168.66:3306/zz_road?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password: cm9vdA==
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    #开启MyBatis的二级缓存
    cache-enabled: true
  mapper-locations: classpath:mybatis/mysql/*.xml
# 日志地址
logging:
  config: classpath:logback.xml
  file:
    path: /log/

# http ip地址配置
system:
  http:
    #实时拥堵
    road:
      host: https://jiaotong.baidu.com/trafficindex/city
      #实时拥堵行政区排行
      districtrank: /districtrank?cityCode=268&roadtype=0
      #郑州市区实时拥堵所有道路
      roadrank0: /roadrank?cityCode=268&roadtype=0
      #郑州市区实时拥堵高速/快速路
      roadrank1: /roadrank?cityCode=268&roadtype=1
      #郑州市区实时拥堵普通道路
      roadrank11: /roadrank?cityCode=268&roadtype=11
    map:
      #百度坐标转换
      host: http://api.map.baidu.com
      path: /ag/coord/convert?from=0&to=4&x=longitude&y=latitude
